COVID 19 DATASET 2020
'1' means yes /female '2' means no/male
97/98 mean missing data
date 9999-99-99 means person didnt die any other date is date died
 AIM To predict different aspects of male patients

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Covid Data.csv')

In [3]:
df

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

SELECTING MALE PATIENTS

In [4]:
df = df[df['SEX']!=1]
df

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
11,2,1,2,2,9999-99-99,2,2,24,97,2,...,2,2,2,2,2,2,2,2,3,2
12,2,1,2,2,9999-99-99,2,2,30,97,2,...,2,2,2,2,2,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [5]:
#Adding new column indicating those who died and  those who are alive in the covid data set
df['STATUS'] =df['DATE_DIED'].apply(lambda x : 'Cured' if '9999-99-99' in x.lower() else 'Died') 
df

/tmp/ipykernel_7501/938325402.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['STATUS'] =df['DATE_DIED'].apply(lambda x : 'Cured' if '9999-99-99' in x.lower() else 'Died')

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU,STATUS
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,1,2,2,1,1,2,5,97,Died
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,3,2,Died
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,1,2,2,2,2,2,3,97,Died
11,2,1,2,2,9999-99-99,2,2,24,97,2,...,2,2,2,2,2,2,2,3,2,Cured
12,2,1,2,2,9999-99-99,2,2,30,97,2,...,2,2,2,2,2,2,2,3,2,Cured
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,7,97,Cured
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,1,2,2,2,2,2,7,2,Cured
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,7,97,Cured
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,7,97,Cured
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,7,97,Cured

In [6]:
#Showing the day and month a patient died
df['DAY_DIED']= df['DATE_DIED'].apply(lambda x : x.split('/')[0])
df['MONTH_DIED']= df['DATE_DIED'].apply(lambda x : x.split('/')[1:-1])#printing middle value of list with three members
df.sample(50)

/tmp/ipykernel_7501/11174361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DAY_DIED']= df['DATE_DIED'].apply(lambda x : x.split('/')[0])
/tmp/ipykernel_7501/11174361.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MONTH_DIED']= df['DATE_DIED'].apply(lambda x : x.split('/')[1:-1])#printing middle value of list with three members

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU,STATUS,DAY_DIED,MONTH_DIED
498354,2,12,2,1,9999-99-99,97,2,47,97,2,...,2,2,1,2,1,3,97,Cured,9999-99-99,[]
355604,2,6,2,1,9999-99-99,97,2,6,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
489049,2,12,2,1,9999-99-99,97,2,47,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
601685,2,12,2,1,9999-99-99,97,2,18,97,2,...,2,2,2,2,1,3,97,Cured,9999-99-99,[]
148258,2,4,2,1,9999-99-99,97,2,32,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
790387,2,12,2,1,9999-99-99,97,2,58,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
758008,2,12,2,1,9999-99-99,97,2,33,97,2,...,2,2,2,2,1,7,97,Cured,9999-99-99,[]
902330,2,12,2,1,9999-99-99,97,2,26,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
275369,1,4,2,1,9999-99-99,97,2,53,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
92139,2,4,2,1,9999-99-99,97,2,33,97,2,...,1,2,2,2,2,3,97,Cured,9999-99-99,[]
479144,2,12,2,1,9999-99-99,97,2,30,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
171003,1,4,2,1,9999-99-99,97,2,24,97,2,...,2,2,2,2,2,6,97,Cured,9999-99-99,[]
469646,2,12,2,1,9999-99-99,97,2,39,97,2,...,2,2,2,2,2,1,97,Cured,9999-99-99,[]
449271,1,12,2,2,09/05/2020,2,1,45,97,1,...,2,2,2,2,2,3,2,Died,09,[05]
643661,2,12,2,1,9999-99-99,97,2,19,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
956565,2,12,2,1,9999-99-99,97,2,85,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
835783,2,12,2,1,9999-99-99,97,2,52,97,1,...,2,2,2,1,2,7,97,Cured,9999-99-99,[]
240439,2,4,2,2,9999-99-99,2,2,52,97,2,...,2,2,1,2,1,7,2,Cured,9999-99-99,[]
9890,2,3,2,1,9999-99-99,97,2,23,97,2,...,2,2,2,2,2,5,97,Cured,9999-99-99,[]
819893,2,12,2,1,9999-99-99,97,2,38,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
689525,2,12,2,1,9999-99-99,97,2,21,97,2,...,2,2,2,2,2,6,97,Cured,9999-99-99,[]
225910,1,4,2,2,9999-99-99,2,2,4,97,2,...,2,2,2,2,2,7,2,Cured,9999-99-99,[]
187467,2,4,2,1,9999-99-99,97,2,5,97,2,...,2,2,2,2,2,6,97,Cured,9999-99-99,[]
209804,2,4,2,2,9999-99-99,2,2,63,97,2,...,2,2,1,2,1,6,2,Cured,9999-99-99,[]
70450,2,4,2,2,9999-99-99,2,1,57,97,2,...,2,2,2,2,2,3,2,Cured,9999-99-99,[]
751054,2,12,2,2,9999-99-99,2,1,47,97,2,...,2,2,2,2,2,7,1,Cured,9999-99-99,[]
966100,1,12,2,1,9999-99-99,97,2,62,97,2,...,2,2,2,2,1,7,97,Cured,9999-99-99,[]
906985,2,12,2,1,9999-99-99,97,1,21,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
235264,2,4,2,2,9999-99-99,2,1,88,97,2,...,1,2,2,2,2,7,2,Cured,9999-99-99,[]
371037,2,6,2,2,9999-99-99,2,2,46,97,2,...,2,2,2,2,2,7,2,Cured,9999-99-99,[]
789905,2,12,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
177836,2,4,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,6,97,Cured,9999-99-99,[]
1034884,2,12,2,1,9999-99-99,97,2,21,97,2,...,2,2,1,2,2,7,97,Cured,9999-99-99,[]
503410,2,12,2,1,9999-99-99,97,2,53,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
60886,1,4,2,1,9999-99-99,97,2,29,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
198963,1,4,2,2,9999-99-99,2,2,61,97,1,...,2,2,2,2,2,6,2,Cured,9999-99-99,[]
120415,1,4,2,1,9999-99-99,97,2,32,97,2,...,1,2,2,2,2,3,97,Cured,9999-99-99,[]
102369,1,4,2,1,9999-99-99,97,2,57,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
426352,2,9,2,1,9999-99-99,97,2,21,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
450889,2,12,2,2,16/05/2020,1,1,67,97,2,...,2,2,2,2,2,6,1,Died,16,[05]
846614,1,12,2,1,9999-99-99,97,2,24,97,2,...,2,2,1,2,2,7,97,Cured,9999-99-99,[]
500012,2,12,2,1,9999-99-99,97,2,26,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
763270,1,12,2,1,9999-99-99,97,2,18,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
664474,1,12,2,1,9999-99-99,97,2,57,97,2,...,2,2,2,2,2,5,97,Cured,9999-99-99,[]
995926,2,12,2,1,9999-99-99,97,2,25,97,2,...,2,2,2,2,1,7,97,Cured,9999-99-99,[]
736245,1,12,2,1,9999-99-99,97,2,40,97,1,...,2,2,1,2,2,7,97,Cured,9999-99-99,[]
378561,1,6,2,1,9999-99-99,97,2,35,97,2,...,2,2,2,2,2,7,97,Cured,9999-99-99,[]
151223,2,4,2,1,9999-99-99,97,2,34,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]
43841,2,4,2,2,21/06/2020,2,1,68,97,1,...,2,1,2,2,2,6,2,Died,21,[06]
105286,2,4,2,1,9999-99-99,97,2,31,97,2,...,2,2,2,2,2,3,97,Cured,9999-99-99,[]

In [7]:
#Number of people who died in 2020 and those that healed
df.STATUS.value_counts()

STATUS
Cured    473971
Died      49540
Name: count, dtype: int64

In [8]:
#returning columns
df.columns

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU', 'STATUS',
       'DAY_DIED', 'MONTH_DIED'],
      dtype='object')

In [9]:
df_out = df.drop(['MEDICAL_UNIT','USMER','SEX','PATIENT_TYPE','INMSUPR','HIPERTENSION','RENAL_CHRONIC','HIPERTENSION','CLASIFFICATION_FINAL','PREGNANT', 'COPD',],axis =1)

In [10]:
df_out

,DATE_DIED,INTUBED,PNEUMONIA,AGE,DIABETES,ASTHMA,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,TOBACCO,ICU,STATUS,DAY_DIED,MONTH_DIED
1,03/06/2020,97,1,72,2,2,2,2,1,2,97,Died,03,[06]
2,09/06/2020,1,2,55,1,2,2,2,2,2,2,Died,09,[06]
4,21/06/2020,97,2,68,1,2,2,2,2,2,97,Died,21,[06]
11,9999-99-99,2,2,24,2,2,2,2,2,2,2,Cured,9999-99-99,[]
12,9999-99-99,2,2,30,2,2,2,2,2,2,2,Cured,9999-99-99,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,9999-99-99,97,2,40,2,2,2,2,2,2,97,Cured,9999-99-99,[]
1048571,9999-99-99,2,2,51,2,2,2,2,2,2,2,Cured,9999-99-99,[]
1048572,9999-99-99,97,2,55,2,2,2,2,2,2,97,Cured,9999-99-99,[]
1048573,9999-99-99,97,2,28,2,2,2,2,2,2,97,Cured,9999-99-99,[]
1048574,9999-99-99,97,2,52,2,2,2,2,2,2,97,Cured,9999-99-99,[]

In [11]:
df_out.to_csv('My Males Covid Data.csv')